
public enum ScoringPattern {
	NONE,
	
	SEVEN_PAIRS, // 30
	
	THIRTEEN_ORPHANS, // 160
	
	CONCEALED_HAND, // 5
	
	ALL_MIDDLE_TILES, // 5
	
	MIXED_ONE_SUIT, // 40
	PURE_ONE_SUIT, // 80
	
	NINE_GATES, // 480
	
	MIXED_LESSER_TERMINALS, // 40
	PURE_LESSER_TERMINALS, // 50
	MIXED_GREATER_TERMINALS, // 100 (+30 Four Triplets implied)
	PURE_GREATER_TERMINALS, // 400
	
	VALUE_HONOR, // 10 - May score multiple times
	
	SMALL_THREE_DRAGONS, // 40 (+20 Value Honor implied)
	BIG_THREE_DRAGONS, // 130 (+30 Value Honor implied)
	
	SMALL_THREE_WINDS, // 30
	SMALL_FOUR_WINDS, // 320
	BIG_THREE_WINDS, // 120
	BIG_FOUR_WINDS, // 400
	
	ALL_HONORS, // 320
	
	FOUR_SEQUENCES, // 5
	
	TWO_IDENTICAL_SEQUENCES, // 10
	THREE_IDENTICAL_SEQUENCES, // 120
	FOUR_IDENTICAL_SEQUENCES, // 480
	TWO_IDENTICAL_SEQUENCES_TWICE, // 60 (+5 Four Sequences implied)
	
	THREE_SIMILAR_SEQUENCES, // 35
	
	NINE_TILE_STRAIGHT, // 40
	
	TWO_CONCEALED_TRIPLETS, // 5
	THREE_CONCEALED_TRIPLETS, // 30
	FOUR_CONCEALED_TRIPLETS, // 125 (+35 Four Triplets & Concealed Hand implied)
	
	FOUR_TRIPLETS, // 30
	
	SMALL_THREE_SIMILAR_TRIPLETS, // 30
	THREE_SIMILAR_TRIPLETS, // 120
	
	THREE_CONSECUTIVE_TRIPLETS, // 100
	FOUR_CONSECUTIVE_TRIPLETS, // 200 (+30 Four Triplets implied)
	
	ONE_KONG, // 5
	TWO_KONG, // 20
	THREE_KONG, // 120
	FOUR_KONG, // 480
}
